import Link from "next/link";
import styles from "./homepage.module.css";

export default function Home() {
  return <div>

  <Link href="/"> <h1>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid earum tempora at. Odio quaerat dicta aspernatur, explicabo accusantium necessitatibus nihil maiores, ratione numquam veritatis expedita rerum quae. Delectus, architecto. Maxime. </h1> Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit mollitia ducimus asperiores a ut delectus harum voluptates facilis? Facilis maiores adipisci, delectus repellendus quos at aut itaque atque doloremque voluptatum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam ullam doloribus perferendis. Numquam animi tempora nam inventore fuga illo praesentium qui reiciendis rerum possimus. Aliquid quod ex repellat! Fugit, quae! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Recusandae quasi tempore dicta modi eum ad, cum repellendus id ut delectus enim ratione odit deleniti blanditiis corrupti ipsum? Sed, quis rem! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus modi quam deleniti repellat ipsa molestiae quo blanditiis quisquam voluptatum quidem. Quas maxime magni qui eveniet! Dignissimos reprehenderit necessitatibus a illo! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque ad nihil accusantium architecto debitis aliquam, similique est, reiciendis reprehenderit vel libero, facere vitae qui voluptatem dolores nobis inventore at quas.
  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Aliquid earum tempora at. Odio quaerat dicta aspernatur, explicabo accusantium necessitatibus nihil maiores, ratione numquam veritatis expedita rerum quae. Delectus, architecto. Maxime. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Impedit mollitia ducimus asperiores a ut delectus harum voluptates facilis? Facilis maiores adipisci, delectus repellendus quos at aut itaque atque doloremque voluptatum. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Aliquam ullam doloribus perferendis. Numquam animi tempora nam inventore fuga illo praesentium qui reiciendis rerum possimus. Aliquid quod ex repellat! Fugit, quae! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Recusandae quasi tempore dicta modi eum ad, cum repellendus id ut delectus enim ratione odit deleniti blanditiis corrupti ipsum? Sed, quis rem! Lorem, ipsum dolor sit amet consectetur adipisicing elit. Accusamus modi quam deleniti repellat ipsa molestiae quo blanditiis quisquam voluptatum quidem. Quas maxime magni qui eveniet! Dignissimos reprehenderit necessitatibus a illo! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque ad nihil accusantium architecto debitis aliquam, similique est, reiciendis reprehenderit vel libero, facere vitae qui voluptatem dolores nobis inventore at quas.
  </Link>
   
    </div>;
}
